name: flutter_no_sleep
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  http: ^0.12.0+2
  flutter_markdown: ^0.2.0
  fancy_bottom_navigation: ^0.3.2
  flutter_svg: ^0.13.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/controversial.svg
    - assets/hot.svg
    - assets/new.svg
    - assets/rising.svg
    - assets/top.svg
    - assets/fonts/Reddit.ttf
  fonts:
    - family: Reddit
      fonts:
        - asset: assets/fonts/Reddit.ttf